# This file was generated by GoReleaser. DO NOT EDIT.
cask "eolwhen" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "939b592befbbd64162a6989cbb1eddf3b2e5a382f011c1cf7f0aea936bb734c5"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b55c4f2dd66f97880acdfa5e57f5ca73b21892b29e24a94390fe5946c36c2a88"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9bf8e9a062f5aba5e1ff91a82ce173c94d23f302a055a5a745f0636a01be1ba8"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "29854621ea8b7b0a26d9da160d2700fe1f560470d5a5782c6ec9c0f6fe323fc7"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eolwhen"
  desc "Say which of a directory's declared versions are out of support."
  homepage "https://github.com/iwamot/eolwhen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eolwhen"

  # No zap stanza required
end
