# This file was generated by GoReleaser. DO NOT EDIT.
cask "eolwhen" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "2e3318e2b767115c74f5224ea0c6294049c6d140df8b8d19f6da26ad47c8df4e"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "96282111924f77cd23ac0b9388340c3e411111cfedd270143635f31a3483c6a0"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "087bd4ddf3df02b3cb58648d054c6201774cb134a8e5762a831cd862770dc2ab"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c7a5ae8e90cccd2335a75707a98d151b8de36b3dd6bda278a0d2f96333a4f174"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eolwhen"
  desc "Say which of a directory's declared versions are out of support."
  homepage "https://github.com/iwamot/eolwhen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eolwhen"

  # No zap stanza required
end
