# This file was generated by GoReleaser. DO NOT EDIT.
cask "eolwhen" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "d7f5693a76eafc2a2fb6dff9f5612de06b7a5359b2112dfd49fd036ba8728854"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a3c8460ceb999635b3ee5012a818f5e7d694817febbe9ff5eb0a37c677f9b4d5"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0e7410d8dbb0c418d66a2335e1aa3db14bce54c46d8514a049f563e5c015c005"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ee5127c36f422d657975aee439b7894b791b37177fbe2c9f10c36280672e0bb"
      url "https://github.com/iwamot/eolwhen/releases/download/v#{version}/eolwhen_#{version}_linux_amd64.tar.gz"
    end
  end

  name "eolwhen"
  desc "Say which of a directory's declared versions are out of support."
  homepage "https://github.com/iwamot/eolwhen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eolwhen"

  # No zap stanza required
end
