# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitignore-prune" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "c47f13292865aecdc3e20376f1930b27af0d123ff6cc4d3f4e2798d5c96773da"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b3b3f6c2cea8d313000cd246ec86b202643fd18cdb80e0ea9a6aa73bdfabd63"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d1b218f79b83f2e926072e7fcb3a60681e116831945dda2d96576cc71a351ce7"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d90d251a88890f54a5eda79524c288e3773906aa7f5c3c3b63d34e507d6b9886"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitignore-prune"
  desc "Detect .gitignore entries that no longer match anything in the working tree."
  homepage "https://github.com/iwamot/gitignore-prune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitignore-prune"

  # No zap stanza required
end
