# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitignore-prune" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "4c2a3fe01675f0f069561f2f2bfeeb4bdf38899514be07d22ccd68709c6c17c9"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f9f06a885507d321132fffdc369b25e24b7feb9867d4110f6b059fcced0a5ad4"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "066145327faa938fa561256f382114af22978e47d5f49fe8b1d2128d5230d0e8"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f4378e8c6d8f6ced6430f8d74edb788fa6c6318bbe4723714bd8d386ae0e3e76"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gitignore-prune"
  desc "Detect .gitignore entries that no longer match anything in the working tree."
  homepage "https://github.com/iwamot/gitignore-prune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitignore-prune"

  # No zap stanza required
end
