# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitignore-prune" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "bf32396006afe9373f51268b2392f46cdc7424e77965e7b8d665936d0632f26d"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "46eb28eab606893fef41cc1ccc0fd6e53e5a5c6a14b6ddcba2d7e482a27d5ae9"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6662178da9c70776f9cf92a9c32cc27534658856432f632934d9af63dc1b5ecf"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "470e62a0860b94b737e795386838f57317b5390b52d06f653a43d5da28a44eb5"
      url "https://github.com/iwamot/gitignore-prune/releases/download/v#{version}/gitignore-prune_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitignore-prune"
  desc "Detect .gitignore entries that no longer match anything in the working tree."
  homepage "https://github.com/iwamot/gitignore-prune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitignore-prune"

  # No zap stanza required

end
