# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkgwhen" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "c001284982b7088b495ec466616eee2f80106739856eda4bc5d00a42c4866f78"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "18bb11302b330e051d673d48ef50b9f6f85bb04d2f8f9161ebd23284b809a9e2"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3555201f91fda53764eeb9eead9bece4cfbe444e668596c4453338ac4fa2b8f4"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "af5a2a14954863ba7fc7c466e4bb1a60e1f256259a64cbd27134ac72d49e8bd2"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pkgwhen"
  desc "List a package's versions with the date each was published."
  homepage "https://github.com/iwamot/pkgwhen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkgwhen"

  # No zap stanza required
end
