# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkgwhen" do
  version "0.5.4"

  on_macos do
    on_arm do
      sha256 "e3e8a005b967a32c919e57e42326097fec7aa17975c2ded4add6ace3fea6263a"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a63e2cb2691583c515d3d33c6bf58803ff39739030dc7063b11333453b09582"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6925334a1ea528d387fa8834da568f1593f0ff9966306e9fabf6a332d3844392"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a55a068b632d695c9a09746532ae6b1dd8a4589356bd89d96e37901326e3b32"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pkgwhen"
  desc "List a package's versions with the date each was published."
  homepage "https://github.com/iwamot/pkgwhen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkgwhen"

  # No zap stanza required
end
