# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkgwhen" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "5b0087e19dd9ea33d1e277f2a543e1d5ff41c98a50aa3090c8d3782cb850bec6"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "439b901839dd2e0992a2e55b7f77d9132fd322e1564f00302b19feedf0bab88b"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "44097731ba25b8fe27fe4c7233cff9e199ece0f99c0a627fb07c718cdc00ff5e"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb34db2bec1f8cfd8f328ccbfcb61cdab262dea9a3f839f21fa33c2f2e166cd4"
      url "https://github.com/iwamot/pkgwhen/releases/download/v#{version}/pkgwhen_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pkgwhen"
  desc "List a package's versions with the date each was published."
  homepage "https://github.com/iwamot/pkgwhen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkgwhen"

  # No zap stanza required
end
