# This file was generated by GoReleaser. DO NOT EDIT.
cask "sub1" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "0d3d7ff63bd5a5e28fc02b68352bba57a9ee9279e3d6a068ec4b985b7f37df15"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ea2cad309b631ead7ac0fe051e7018d1983babae333c421042961452a2f73ad"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "709194c41eb4decd5c062d6a73d75f852c37a8a2c27f5bc6d9f1fd562d0b0705"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e96b944cc79fa7d987e4868f27f30704c853ded7b24b1c4f3c47a10e7cc3f21"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sub1"
  desc "Replace a literal text block in a file, exactly once."
  homepage "https://github.com/iwamot/sub1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sub1"

  # No zap stanza required
end
