# This file was generated by GoReleaser. DO NOT EDIT.
cask "sub1" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "5873f965f89d103d04b5b5050351f8c1dc595b8330d08d5d37ba6514520d2d0f"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f122a26e535b806febf00996be83cfc697011b87a2d770649aadd2d33b5abe35"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "817833b6bdbc041f59ccd459f87b13b80728145b48217fc627b92d1dfcb34fb5"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c1c68dd564b46652c85b5ea941407202d84790b201a5766d984b083f09a72389"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sub1"
  desc "Replace a literal text block in a file, exactly once."
  homepage "https://github.com/iwamot/sub1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sub1"

  # No zap stanza required
end
