# This file was generated by GoReleaser. DO NOT EDIT.
cask "sub1" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "3c0dbb043a1b9b420de80074f27eca430903de76c808f304e1df9f2e48214b07"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e5e85191c9214be620b141ea3c761857d52fb7064e9d7a1eae6456a365c14cb"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5de01c30d5dcdcb71ee78e798ecdadaef16255298b6a6128e980079a254d4eac"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7db7e7d3049bcba87b4d2040e21620362aa7f6100513f74bd2d36fad48ca2b43"
      url "https://github.com/iwamot/sub1/releases/download/v#{version}/sub1_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sub1"
  desc "Replace a literal text block in a file, exactly once."
  homepage "https://github.com/iwamot/sub1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sub1"

  # No zap stanza required
end
