name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: write  # to create and publish the GitHub Release
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: iwamot/actions/release-draft@877dcb21b865c1824a70cfebde66313b1d58a860 # v2.8.1
      - uses: iwamot/actions/release-publish@877dcb21b865c1824a70cfebde66313b1d58a860 # v2.8.1
